#!/usr/bin/env python3
"""
workspace_agent.py - Intelligent Workspace Setup & Validation Agent

This agent helps you set up and validate your lineage extraction workspace.
It creates directory structures, validates file placement, checks dependencies,
and provides interactive guidance.

Usage:
    python workspace_agent.py setup      # Interactive setup
    python workspace_agent.py validate   # Validate existing workspace
    python workspace_agent.py check      # Pre-flight check
    python workspace_agent.py repair     # Fix common issues
"""

import os
import sys
import json
import shutil
import zipfile
from pathlib import Path
from typing import Dict, List, Tuple, Optional
from datetime import datetime
import subprocess

# ANSI color codes for pretty output
class Colors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKCYAN = '\033[96m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'

def print_header(text):
    print(f"\n{Colors.HEADER}{Colors.BOLD}{'='*70}{Colors.ENDC}")
    print(f"{Colors.HEADER}{Colors.BOLD}{text}{Colors.ENDC}")
    print(f"{Colors.HEADER}{Colors.BOLD}{'='*70}{Colors.ENDC}\n")

def print_success(text):
    print(f"{Colors.OKGREEN}✓ {text}{Colors.ENDC}")

def print_warning(text):
    print(f"{Colors.WARNING}⚠️  {text}{Colors.ENDC}")

def print_error(text):
    print(f"{Colors.FAIL}❌ {text}{Colors.ENDC}")

def print_info(text):
    print(f"{Colors.OKCYAN}ℹ️  {text}{Colors.ENDC}")


class WorkspaceAgent:
    """Intelligent agent for workspace setup and validation"""
    
    # Hierarchical workspace structure
    WORKSPACE_STRUCTURE = {
        'source_code': {
            'description': 'Core pipeline code',
            'required_files': ['demo.py'],
            'optional_files': ['chat_interface.py', 'demo_llm_chat.py'],
            'create': True
        },
        'input_data': {
            'description': 'Source data files',
            'required_files': ['store-procedure-table.zip'],
            'optional_files': ['imperva_small.xlsx', 'annotated_groundtruth.yaml'],
            'create': True
        },
        'output_artifacts': {
            'description': 'Generated outputs',
            'required_files': [],  # Generated by pipeline
            'optional_files': [],
            'create': True
        },
        'output_artifacts/out_lineage': {
            'description': 'Excel reports',
            'required_files': [],  # Generated by pipeline
            'optional_files': [],
            'create': True
        },
        'intermediate': {
            'description': 'Temporary working files',
            'required_files': [],  # Generated by pipeline
            'optional_files': [],
            'create': True
        },
        'documentation': {
            'description': 'Project documentation',
            'required_files': [],
            'optional_files': [
                'PROJECT_MANIFEST_V4.md',
                'WORKSPACE_SETUP_V4.md',
                'RUNNING_INSTRUCTIONS_V4.md',
                'FAQ_V4.md',
                'QUICKSTART_V4.md'
            ],
            'create': True
        },
        'logs': {
            'description': 'Execution logs (optional)',
            'required_files': [],
            'optional_files': [],
            'create': False  # Optional
        }
    }
    
    # Required Python dependencies
    REQUIRED_PACKAGES = [
        'pandas',
        'numpy',
        'scikit-learn',
        'openpyxl',
        'pyyaml'
    ]
    
    OPTIONAL_PACKAGES = [
        'sentence-transformers',  # For semantic embeddings
        'anthropic'  # For LLM chat
    ]
    
    def __init__(self, workspace_path: Optional[Path] = None):
        self.workspace_path = workspace_path or Path.cwd()
        self.workspace_path = self.workspace_path.resolve()
        self.issues = []
        self.warnings = []
        self.info = []
        
    def print_banner(self):
        """Print agent banner"""
        print(f"""
{Colors.HEADER}{Colors.BOLD}
╔════════════════════════════════════════════════════════════════════╗
║                    WORKSPACE SETUP AGENT v4.0                      ║
║              Intelligent Workspace Management & Validation          ║
╚════════════════════════════════════════════════════════════════════╝
{Colors.ENDC}
        """)
    
    def setup_workspace(self, mode: str = 'organized'):
        """
        Interactive workspace setup
        
        Modes:
        - minimal: Single directory (testing)
        - organized: Full structure (recommended)
        - custom: User-guided setup
        """
        self.print_banner()
        print_header(f"WORKSPACE SETUP - {mode.upper()} MODE")
        
        print(f"📁 Workspace location: {Colors.BOLD}{self.workspace_path}{Colors.ENDC}\n")
        
        if mode == 'organized':
            self._setup_organized()
        elif mode == 'minimal':
            self._setup_minimal()
        elif mode == 'custom':
            self._setup_custom()
        else:
            print_error(f"Unknown mode: {mode}")
            sys.exit(1)
    
    def _setup_organized(self):
        """Set up organized workspace structure (recommended)"""
        print_info("Creating organized workspace structure...")
        print()
        
        # Create directory structure
        for dir_path, config in self.WORKSPACE_STRUCTURE.items():
            if config['create']:
                full_path = self.workspace_path / dir_path
                full_path.mkdir(parents=True, exist_ok=True)
                print_success(f"Created: {dir_path}/ - {config['description']}")
        
        print()
        print_header("DIRECTORY STRUCTURE CREATED")
        
        # Print tree
        self._print_workspace_tree()
        
        print()
        print_header("NEXT STEPS")
        
        print(f"""
{Colors.BOLD}1. Place source code files:{Colors.ENDC}
   {Colors.OKCYAN}cd {self.workspace_path}/source_code{Colors.ENDC}
   • demo.py (required)
   • chat_interface.py (optional)
   • demo_llm_chat.py (optional)

{Colors.BOLD}2. Place input data files:{Colors.ENDC}
   {Colors.OKCYAN}cd {self.workspace_path}/input_data{Colors.ENDC}
   • store-procedure-table.zip (required)
   • imperva_small.xlsx (optional)
   • annotated_groundtruth.yaml (optional)

{Colors.BOLD}3. Place documentation:{Colors.ENDC}
   {Colors.OKCYAN}cd {self.workspace_path}/documentation{Colors.ENDC}
   • *.md files (optional but recommended)

{Colors.BOLD}4. Validate workspace:{Colors.ENDC}
   {Colors.OKCYAN}python workspace_agent.py validate{Colors.ENDC}

{Colors.BOLD}5. Run pipeline:{Colors.ENDC}
   {Colors.OKCYAN}cd {self.workspace_path}/source_code{Colors.ENDC}
   {Colors.OKCYAN}python demo.py{Colors.ENDC}
        """)
        
        # Create README in each directory
        self._create_directory_readmes()
        
        print_success(f"Workspace setup complete at: {self.workspace_path}")
    
    def _setup_minimal(self):
        """Set up minimal workspace (single directory)"""
        print_info("Creating minimal workspace structure...")
        print()
        
        print_success(f"Workspace: {self.workspace_path}")
        print_info("All files will be placed in this single directory")
        
        print()
        print_header("FILE PLACEMENT")
        
        print(f"""
{Colors.BOLD}Place these files in:{Colors.ENDC} {Colors.OKCYAN}{self.workspace_path}{Colors.ENDC}

{Colors.BOLD}Required:{Colors.ENDC}
  • demo.py
  • store-procedure-table.zip

{Colors.BOLD}Optional:{Colors.ENDC}
  • chat_interface.py
  • demo_llm_chat.py
  • imperva_small.xlsx
  • annotated_groundtruth.yaml

{Colors.BOLD}Generated outputs will appear in same directory:{Colors.ENDC}
  • demo.enriched.yaml
  • lineage_rag.pkl
  • validation_report.json
  • out_lineage/ (directory)
  • sp_demo/ (temporary directory)
        """)
        
        print_success("Minimal workspace configured")
    
    def _setup_custom(self):
        """Interactive custom setup"""
        print_info("Custom setup mode - answer questions to configure")
        print()
        
        # Ask about each directory
        dirs_to_create = []
        for dir_path, config in self.WORKSPACE_STRUCTURE.items():
            response = input(f"Create {dir_path}/ ({config['description']})? [Y/n]: ").strip().lower()
            if response in ['', 'y', 'yes']:
                dirs_to_create.append((dir_path, config))
        
        print()
        print_info(f"Creating {len(dirs_to_create)} directories...")
        
        for dir_path, config in dirs_to_create:
            full_path = self.workspace_path / dir_path
            full_path.mkdir(parents=True, exist_ok=True)
            print_success(f"Created: {dir_path}/")
        
        print()
        print_success("Custom workspace setup complete")
    
    def validate_workspace(self):
        """Validate existing workspace structure and files"""
        self.print_banner()
        print_header("WORKSPACE VALIDATION")
        
        print(f"📁 Validating: {Colors.BOLD}{self.workspace_path}{Colors.ENDC}\n")
        
        self.issues = []
        self.warnings = []
        self.info = []
        
        # Check directory structure
        self._validate_directory_structure()
        
        # Check required files
        self._validate_required_files()
        
        # Check optional files
        self._validate_optional_files()
        
        # Check dependencies
        self._validate_dependencies()
        
        # Check disk space
        self._validate_disk_space()
        
        # Check permissions
        self._validate_permissions()
        
        # Print report
        self._print_validation_report()
        
        # Return status
        return len(self.issues) == 0
    
    def _validate_directory_structure(self):
        """Check if expected directories exist"""
        print_info("Checking directory structure...")
        
        found_dirs = []
        missing_dirs = []
        
        for dir_path, config in self.WORKSPACE_STRUCTURE.items():
            if not config['create']:
                continue  # Skip optional directories
                
            full_path = self.workspace_path / dir_path
            if full_path.exists() and full_path.is_dir():
                found_dirs.append(dir_path)
            else:
                missing_dirs.append(dir_path)
        
        if missing_dirs:
            self.warnings.append(f"Missing directories: {', '.join(missing_dirs)}")
            print_warning(f"Missing {len(missing_dirs)} directories (can be created)")
        
        if found_dirs:
            print_success(f"Found {len(found_dirs)}/{len(found_dirs) + len(missing_dirs)} expected directories")
    
    def _validate_required_files(self):
        """Check if required files exist"""
        print_info("Checking required files...")
        
        required_files = []
        for dir_path, config in self.WORKSPACE_STRUCTURE.items():
            for filename in config['required_files']:
                required_files.append((dir_path, filename))
        
        missing_required = []
        found_required = []
        
        for dir_path, filename in required_files:
            full_path = self.workspace_path / dir_path / filename
            if full_path.exists():
                found_required.append(f"{dir_path}/{filename}")
            else:
                missing_required.append(f"{dir_path}/{filename}")
        
        if missing_required:
            self.issues.extend([f"Missing required file: {f}" for f in missing_required])
            print_error(f"Missing {len(missing_required)} required files")
        else:
            if found_required:
                print_success("All required files present")
    
    def _validate_optional_files(self):
        """Check optional files and provide info"""
        print_info("Checking optional files...")
        
        optional_files = []
        for dir_path, config in self.WORKSPACE_STRUCTURE.items():
            for filename in config['optional_files']:
                optional_files.append((dir_path, filename))
        
        found_optional = []
        missing_optional = []
        
        for dir_path, filename in optional_files:
            full_path = self.workspace_path / dir_path / filename
            if full_path.exists():
                found_optional.append(f"{dir_path}/{filename}")
            else:
                missing_optional.append(f"{dir_path}/{filename}")
        
        if found_optional:
            print_success(f"Found {len(found_optional)} optional files")
        
        if missing_optional:
            self.info.append(f"Optional files not present: {len(missing_optional)} (OK)")
    
    def _validate_dependencies(self):
        """Check Python dependencies"""
        print_info("Checking dependencies...")
        
        missing_required = []
        missing_optional = []
        
        for package in self.REQUIRED_PACKAGES:
            try:
                __import__(package.replace('-', '_'))
            except ImportError:
                missing_required.append(package)
        
        for package in self.OPTIONAL_PACKAGES:
            try:
                __import__(package.replace('-', '_'))
            except ImportError:
                missing_optional.append(package)
        
        if missing_required:
            self.issues.append(f"Missing required packages: {', '.join(missing_required)}")
            print_error(f"Missing {len(missing_required)} required packages")
        else:
            print_success("All required packages installed")
        
        if missing_optional:
            self.warnings.append(f"Missing optional packages: {', '.join(missing_optional)}")
            print_warning(f"Missing {len(missing_optional)} optional packages (features limited)")
    
    def _validate_disk_space(self):
        """Check available disk space"""
        print_info("Checking disk space...")
        
        stat = shutil.disk_usage(self.workspace_path)
        free_mb = stat.free / (1024 * 1024)
        
        if free_mb < 100:
            self.issues.append(f"Low disk space: {free_mb:.0f} MB available (need 100+ MB)")
            print_error(f"Low disk space: {free_mb:.0f} MB")
        elif free_mb < 500:
            self.warnings.append(f"Limited disk space: {free_mb:.0f} MB available (recommended 500+ MB)")
            print_warning(f"Limited disk space: {free_mb:.0f} MB")
        else:
            print_success(f"Sufficient disk space: {free_mb:.0f} MB available")
    
    def _validate_permissions(self):
        """Check write permissions"""
        print_info("Checking permissions...")
        
        test_file = self.workspace_path / '.workspace_agent_test'
        try:
            test_file.touch()
            test_file.unlink()
            print_success("Write permissions OK")
        except Exception as e:
            self.issues.append(f"No write permissions: {e}")
            print_error("No write permissions")
    
    def _print_validation_report(self):
        """Print comprehensive validation report"""
        print()
        print_header("VALIDATION REPORT")
        
        # Issues (critical)
        if self.issues:
            print(f"\n{Colors.FAIL}{Colors.BOLD}❌ ISSUES (must fix):{Colors.ENDC}")
            for issue in self.issues:
                print(f"  {Colors.FAIL}• {issue}{Colors.ENDC}")
        
        # Warnings (should fix)
        if self.warnings:
            print(f"\n{Colors.WARNING}{Colors.BOLD}⚠️  WARNINGS (should fix):{Colors.ENDC}")
            for warning in self.warnings:
                print(f"  {Colors.WARNING}• {warning}{Colors.ENDC}")
        
        # Info (optional)
        if self.info:
            print(f"\n{Colors.OKCYAN}{Colors.BOLD}ℹ️  INFO:{Colors.ENDC}")
            for info_item in self.info:
                print(f"  {Colors.OKCYAN}• {info_item}{Colors.ENDC}")
        
        # Overall status
        print()
        if not self.issues and not self.warnings:
            print(f"{Colors.OKGREEN}{Colors.BOLD}✅ VALIDATION PASSED - Workspace is ready!{Colors.ENDC}")
        elif not self.issues:
            print(f"{Colors.WARNING}{Colors.BOLD}⚠️  VALIDATION PASSED WITH WARNINGS{Colors.ENDC}")
            print(f"{Colors.WARNING}   Workspace is usable but some optional features may not work{Colors.ENDC}")
        else:
            print(f"{Colors.FAIL}{Colors.BOLD}❌ VALIDATION FAILED - Fix issues before running pipeline{Colors.ENDC}")
    
    def check_preflight(self):
        """Quick pre-flight check before running pipeline"""
        self.print_banner()
        print_header("PRE-FLIGHT CHECK")
        
        checks = []
        
        # Python version
        py_version = sys.version_info
        if py_version >= (3, 8):
            checks.append(("Python version", True, f"{py_version.major}.{py_version.minor}"))
        else:
            checks.append(("Python version", False, f"{py_version.major}.{py_version.minor} (need 3.8+)"))
        
        # Required files
        demo_py = (self.workspace_path / "demo.py").exists()
        checks.append(("demo.py", demo_py, "Found" if demo_py else "Missing"))
        
        zip_file = (self.workspace_path / "store-procedure-table.zip").exists()
        checks.append(("store-procedure-table.zip", zip_file, "Found" if zip_file else "Missing"))
        
        # Dependencies
        deps_ok = all(self._check_package(pkg) for pkg in self.REQUIRED_PACKAGES)
        checks.append(("Required packages", deps_ok, "All installed" if deps_ok else "Some missing"))
        
        # Disk space
        free_mb = shutil.disk_usage(self.workspace_path).free / (1024 * 1024)
        space_ok = free_mb > 100
        checks.append(("Disk space", space_ok, f"{free_mb:.0f} MB available"))
        
        # Permissions
        try:
            test_file = self.workspace_path / '.test'
            test_file.touch()
            test_file.unlink()
            perms_ok = True
        except:
            perms_ok = False
        checks.append(("Write permissions", perms_ok, "OK" if perms_ok else "Failed"))
        
        # Print results
        print()
        max_len = max(len(check[0]) for check in checks)
        for name, passed, details in checks:
            status = "✓" if passed else "✗"
            color = Colors.OKGREEN if passed else Colors.FAIL
            print(f"  {color}{status}{Colors.ENDC} {name.ljust(max_len)} : {details}")
        
        print()
        all_passed = all(check[1] for check in checks)
        if all_passed:
            print_success("All pre-flight checks passed - ready to run!")
            return True
        else:
            print_error("Some pre-flight checks failed - fix issues before running")
            return False
    
    def repair_workspace(self):
        """Attempt to fix common issues"""
        self.print_banner()
        print_header("WORKSPACE REPAIR")
        
        print_info("Analyzing workspace and attempting repairs...")
        print()
        
        repairs = []
        
        # Create missing directories
        for dir_path, config in self.WORKSPACE_STRUCTURE.items():
            if config['create']:
                full_path = self.workspace_path / dir_path
                if not full_path.exists():
                    full_path.mkdir(parents=True, exist_ok=True)
                    repairs.append(f"Created directory: {dir_path}")
                    print_success(f"Created: {dir_path}/")
        
        # Install missing packages (if pip available)
        try:
            for package in self.REQUIRED_PACKAGES:
                if not self._check_package(package):
                    print_info(f"Installing {package}...")
                    result = subprocess.run(
                        [sys.executable, "-m", "pip", "install", package, "--break-system-packages"],
                        capture_output=True,
                        text=True
                    )
                    if result.returncode == 0:
                        repairs.append(f"Installed package: {package}")
                        print_success(f"Installed: {package}")
                    else:
                        print_warning(f"Failed to install: {package}")
        except Exception as e:
            print_warning(f"Could not auto-install packages: {e}")
        
        print()
        if repairs:
            print_success(f"Applied {len(repairs)} repairs")
        else:
            print_info("No repairs needed")
    
    def _check_package(self, package: str) -> bool:
        """Check if a package is installed"""
        try:
            __import__(package.replace('-', '_'))
            return True
        except ImportError:
            return False
    
    def _print_workspace_tree(self):
        """Print ASCII tree of workspace structure"""
        print(f"""
{Colors.BOLD}{self.workspace_path.name}/{Colors.ENDC}
├── 📂 {Colors.OKCYAN}source_code/{Colors.ENDC}           # Core pipeline code
│   ├── demo.py                   # Main pipeline (required)
│   ├── chat_interface.py         # Chat interface (optional)
│   └── demo_llm_chat.py          # Demo script (optional)
│
├── 📂 {Colors.OKCYAN}input_data/{Colors.ENDC}            # Source data files
│   ├── store-procedure-table.zip # DDL + SP (required)
│   ├── imperva_small.xlsx        # Runtime logs (optional)
│   └── annotated_groundtruth.yaml # Validation (optional)
│
├── 📂 {Colors.OKCYAN}output_artifacts/{Colors.ENDC}      # Generated outputs
│   ├── demo.enriched.yaml        # Knowledge graph (auto-generated)
│   ├── lineage_rag.pkl           # RAG library (auto-generated)
│   ├── validation_report.json    # Metrics (auto-generated)
│   └── out_lineage/              # Excel reports (auto-generated)
│       ├── table_lineage.xlsx
│       └── attribute_lineage.xlsx
│
├── 📂 {Colors.OKCYAN}intermediate/{Colors.ENDC}          # Temporary files
│   └── sp_demo/                  # Extracted SP files (auto-generated)
│
├── 📂 {Colors.OKCYAN}documentation/{Colors.ENDC}         # Project docs
│   ├── PROJECT_MANIFEST_V4.md
│   ├── WORKSPACE_SETUP_V4.md
│   ├── RUNNING_INSTRUCTIONS_V4.md
│   ├── FAQ_V4.md
│   └── ...
│
└── 📂 {Colors.OKCYAN}logs/{Colors.ENDC}                  # Execution logs (optional)
    └── pipeline_execution.log
        """)
    
    def _create_directory_readmes(self):
        """Create README files in each directory"""
        readmes = {
            'source_code': """# Source Code Directory

Place your pipeline code files here:
- demo.py (required)
- chat_interface.py (optional)
- demo_llm_chat.py (optional)

Run pipeline from this directory:
    python demo.py
""",
            'input_data': """# Input Data Directory

Place your source data files here:
- store-procedure-table.zip (required) - DDL + Stored Procedures
- imperva_small.xlsx (optional) - Runtime telemetry logs
- annotated_groundtruth.yaml (optional) - Validation ground truth

These files will be read by the pipeline.
""",
            'output_artifacts': """# Output Artifacts Directory

Generated outputs will appear here:
- demo.enriched.yaml - Knowledge graph
- lineage_rag.pkl - RAG library (~17 MB)
- validation_report.json - Quality metrics
- out_lineage/ - Excel reports

These files are auto-generated by the pipeline.
DO NOT edit manually.
""",
            'documentation': """# Documentation Directory

Place documentation files here:
- PROJECT_MANIFEST_V4.md
- WORKSPACE_SETUP_V4.md
- RUNNING_INSTRUCTIONS_V4.md
- FAQ_V4.md
- And other .md files

These provide guidance on using the pipeline.
"""
        }
        
        for dir_name, content in readmes.items():
            readme_path = self.workspace_path / dir_name / "README.md"
            if not readme_path.exists():
                readme_path.write_text(content)
    
    def generate_status_report(self):
        """Generate comprehensive status report"""
        self.print_banner()
        print_header("WORKSPACE STATUS REPORT")
        
        report = {
            'timestamp': datetime.now().isoformat(),
            'workspace_path': str(self.workspace_path),
            'structure': {},
            'files': {},
            'dependencies': {},
            'system': {}
        }
        
        # Directory structure
        for dir_path, config in self.WORKSPACE_STRUCTURE.items():
            full_path = self.workspace_path / dir_path
            report['structure'][dir_path] = {
                'exists': full_path.exists(),
                'description': config['description'],
                'required': config['create']
            }
        
        # Files
        all_files = list(self.workspace_path.rglob('*'))
        report['files']['total'] = len([f for f in all_files if f.is_file()])
        report['files']['directories'] = len([f for f in all_files if f.is_dir()])
        
        # Dependencies
        for package in self.REQUIRED_PACKAGES:
            report['dependencies'][package] = self._check_package(package)
        
        # System
        stat = shutil.disk_usage(self.workspace_path)
        report['system']['disk_free_mb'] = stat.free / (1024 * 1024)
        report['system']['python_version'] = f"{sys.version_info.major}.{sys.version_info.minor}"
        
        # Save report
        report_path = self.workspace_path / 'workspace_status.json'
        with open(report_path, 'w') as f:
            json.dump(report, f, indent=2)
        
        print_success(f"Status report saved to: {report_path}")
        
        # Print summary
        print()
        print(f"{Colors.BOLD}Summary:{Colors.ENDC}")
        print(f"  Workspace: {self.workspace_path}")
        print(f"  Files: {report['files']['total']}")
        print(f"  Dependencies: {sum(report['dependencies'].values())}/{len(report['dependencies'])}")
        print(f"  Disk space: {report['system']['disk_free_mb']:.0f} MB available")


def main():
    """Main entry point"""
    import argparse
    
    parser = argparse.ArgumentParser(
        description='Workspace Setup & Validation Agent',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python workspace_agent.py setup                  # Interactive setup (organized mode)
  python workspace_agent.py setup --mode minimal   # Minimal setup
  python workspace_agent.py validate               # Validate workspace
  python workspace_agent.py check                  # Pre-flight check
  python workspace_agent.py repair                 # Fix issues
  python workspace_agent.py status                 # Generate status report
        """
    )
    
    parser.add_argument(
        'command',
        choices=['setup', 'validate', 'check', 'repair', 'status'],
        help='Command to execute'
    )
    
    parser.add_argument(
        '--mode',
        choices=['minimal', 'organized', 'custom'],
        default='organized',
        help='Setup mode (default: organized)'
    )
    
    parser.add_argument(
        '--path',
        type=Path,
        default=Path.cwd(),
        help='Workspace path (default: current directory)'
    )
    
    args = parser.parse_args()
    
    # Create agent
    agent = WorkspaceAgent(args.path)
    
    # Execute command
    if args.command == 'setup':
        agent.setup_workspace(mode=args.mode)
    
    elif args.command == 'validate':
        success = agent.validate_workspace()
        sys.exit(0 if success else 1)
    
    elif args.command == 'check':
        success = agent.check_preflight()
        sys.exit(0 if success else 1)
    
    elif args.command == 'repair':
        agent.repair_workspace()
    
    elif args.command == 'status':
        agent.generate_status_report()


if __name__ == "__main__":
    main()
